---
id: Yaml
name: Yaml
full: YAML parsing and writing library
description: >
  Classes for parsing YAML files into PHP arrays, and dumping PHP arrays into
  YAML encoding.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Yaml
authors:
  -
    name: Mike Naberezny
    user: mnaberez
    email: mike@maintainable.com
    active: true
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 2.1.0
  api: 1.0.0
state:
  release: stable
  api: stable
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^5.3 || ^7
    ext:
      ctype: '*'
    pear:
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Util: ^2
  optional:
    pear:
      pear.horde.org/Horde_Test: ^2.1
