---
id: Yaml
name: Yaml
full: YAML parsing and writing library
description: >-
  A library for parsing YAML files into PHP arrays, and dumping PHP arrays into
  YAML encoding.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Yaml
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Mike Naberezny
    user: mnaberez
    email: mike@maintainable.com
    active: false
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha4
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^7
    ext:
      ctype: '*'
    composer:
      horde/exception: ^3
      horde/util: ^3
  optional:
    composer:
      horde/test: ^3
