<?php

declare(strict_types=1);

require __DIR__ . '/../vendor/autoload.php';

$suitePath = __DIR__ . '/../test/fixtures/yaml-test-suite';
$manifestPath = __DIR__ . '/../test/fixtures/conformance/yaml-test-suite-status.php';

$manifest = require $manifestPath;

// Drop "no in.yaml" entries — these are multi-format parents now
// expanded into subcases.
$drops = [];
foreach ($manifest as $id => $status) {
    if (str_contains($status, 'no in.yaml')) {
        $drops[] = $id;
    }
}
foreach ($drops as $id) {
    unset($manifest[$id]);
}

// Triage all subcases.
$added = 0;
foreach (glob($suitePath . '/*', GLOB_ONLYDIR) ?: [] as $caseDir) {
    $id = basename($caseDir);
    if ($id === 'name' || $id === 'tags') {
        continue;
    }
    if (file_exists($caseDir . '/in.yaml')) {
        continue;
    }
    foreach (glob($caseDir . '/[0-9][0-9]', GLOB_ONLYDIR) ?: [] as $sub) {
        $subId = $id . '/' . basename($sub);
        if (isset($manifest[$subId])) {
            continue;
        }
        $errorMarker = file_exists($sub . '/error');
        $inFile = $sub . '/in.yaml';
        if (!file_exists($inFile)) {
            continue;
        }
        $yaml = file_get_contents($inFile);
        try {
            @(new Horde\Yaml\Document\YamlStringLoader())->load($yaml);
            $manifest[$subId] = $errorMarker
                ? 'skip:lenient acceptance of invalid YAML (out-of-scope strictness)'
                : 'pass';
        } catch (Throwable) {
            $manifest[$subId] = $errorMarker
                ? 'error'
                : 'skip:loader threw ParseException (out-of-scope feature or parse limitation)';
        }
        $added++;
    }
}

ksort($manifest);

// Re-emit.
$lines = ["<?php", "", "declare(strict_types=1);", "", "/**"];
$lines[] = " * Conformance status manifest for the yaml-test-suite cases.";
$lines[] = " *";
$lines[] = " * Generated by scripts/triage-yaml-test-suite.php.";
$lines[] = " *";
$lines[] = " * Each entry maps a case ID to a status:";
$lines[] = " *   - 'pass'          — loader must accept this input";
$lines[] = " *   - 'error'         — loader must throw a ParseException";
$lines[] = " *   - 'skip:<reason>' — out-of-scope or unsupported (documented)";
$lines[] = " *";
$lines[] = " * Multi-format directories are listed as PARENT/NN composite IDs.";
$lines[] = " *";
$lines[] = " * @return array<string, string>";
$lines[] = " */";
$lines[] = "";
$lines[] = "return array (";
foreach ($manifest as $id => $status) {
    $lines[] = "  '" . $id . "' => '" . str_replace("'", "\\'", $status) . "',";
}
$lines[] = ");";
$lines[] = "";

file_put_contents($manifestPath, implode("\n", $lines));

echo "Dropped " . count($drops) . " 'no in.yaml' entries.\n";
echo "Added $added subcase entries.\n";
echo "Manifest now has " . count($manifest) . " entries.\n";
