<?php

declare(strict_types=1);

/**
 * Triage script for the yaml-test-suite cases.
 *
 * Walks every case directory and classifies each as pass/error/skip
 * based on:
 *   - the presence of an `error` marker file in the case directory
 *     (case must throw)
 *   - whether our loader actually succeeds or throws
 *
 * Cases where the marker says error and we throw: pass-as-error.
 * Cases where there's no error marker and we load cleanly: pass.
 * Cases where the marker says error but we DON'T throw: skip with
 *   "feature unsupported, lenient acceptance".
 * Cases where there's no error marker but we throw: skip with
 *   "feature unsupported, parse failure" plus the exception class.
 *
 * Output is a PHP file at the manifest path. Run from the repo root:
 *
 *     php scripts/triage-yaml-test-suite.php
 */

require __DIR__ . '/../vendor/autoload.php';

use Horde\Yaml\Document\YamlStringLoader;

$suite = __DIR__ . '/../test/fixtures/yaml-test-suite';
$manifestPath = __DIR__ . '/../test/fixtures/conformance/yaml-test-suite-status.php';

if (!is_dir($suite)) {
    fwrite(STDERR, "yaml-test-suite submodule not initialized\n");
    exit(1);
}

$entries = glob("$suite/*", GLOB_ONLYDIR) ?: [];
$results = [];
$counts = ['pass' => 0, 'error' => 0, 'skip-unsupported-load' => 0, 'skip-unsupported-error' => 0];

foreach ($entries as $caseDir) {
    $id = basename($caseDir);
    if ($id === 'name' || $id === 'tags') {
        continue;
    }

    $inFile = "$caseDir/in.yaml";
    if (!file_exists($inFile)) {
        $results[$id] = 'skip:no in.yaml';
        continue;
    }

    $yaml = file_get_contents($inFile);
    $expectsError = file_exists("$caseDir/error");

    $loader = new YamlStringLoader();
    $loadOk = false;
    $loadException = null;
    try {
        $loader->load($yaml);
        $loadOk = true;
    } catch (Throwable $e) {
        $loadException = $e;
    }

    if ($expectsError) {
        if ($loadOk) {
            // Loader accepted invalid input; mark as skip with reason.
            $results[$id] = 'skip:lenient acceptance of invalid YAML (out-of-scope strictness)';
            $counts['skip-unsupported-error']++;
        } else {
            // Loader rejected invalid input as expected.
            $results[$id] = 'error';
            $counts['error']++;
        }
        continue;
    }

    if ($loadOk) {
        $results[$id] = 'pass';
        $counts['pass']++;
        continue;
    }

    // No error marker but we threw — record as skip with the exception
    // class so the manifest documents the reason.
    $exClass = $loadException::class;
    $shortClass = substr($exClass, strrpos($exClass, '\\') + 1);
    $results[$id] = "skip:loader threw $shortClass (out-of-scope feature or parse limitation)";
    $counts['skip-unsupported-load']++;
}

ksort($results);

$header = <<<'PHP'
    <?php

    declare(strict_types=1);

    /**
     * Conformance status manifest for the yaml-test-suite cases.
     *
     * Generated by scripts/triage-yaml-test-suite.php.
     *
     * Each entry maps a case ID to a status:
     *   - 'pass'          — loader must accept this input
     *   - 'error'         — loader must throw a ParseException
     *   - 'skip:<reason>' — out-of-scope or unsupported (documented)
     *
     * @return array<string, string>
     */

    return
    PHP;

$body = var_export($results, true);
file_put_contents($manifestPath, $header . ' ' . $body . ";\n");

fprintf(STDOUT, "Triage results:\n");
foreach ($counts as $k => $v) {
    fprintf(STDOUT, "  %-30s %d\n", $k, $v);
}
fprintf(STDOUT, "Total cases: %d\n", count($results));
fprintf(STDOUT, "Manifest written to: %s\n", $manifestPath);
